version: "3.8"
name: ${APP_NAME}

services:

  # PHP APPS
  php_app:
    container_name: ${APP_NAME}
    image: ${APP_NAME}/php
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        - COMPOSER_VERSION=latest
        - XDEBUG_VERSION=latest
    volumes:
      - "php_app:/var/www/html"
      - "./logs/xdebug:/var/log/xdebug"
      - "./ssl/ca/ca.crt:/usr/local/share/cert_install/ca.crt"
      - "./volumes/www-home:/home/www-data"
      # Uncomment for ssh These files will be copied upon
      # - "./conf/ssh/config:/home/www-data/.ssh_settings/config"
      # Replace ssh keys here
      # - "~/.ssh/pc_magas.pub:/home/www-data/.ssh_settings/pc_magas.pub"
      # - "~/.ssh/pc_magas:/home/www-data/.ssh_settings/pc_magas"
    networks:
      default:
    env_file: env/php.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Supportive services
  
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx
    networks:
      default:
        ipv4_address: ${IP_BASE}.2
    volumes:
      - "php_app:/var/www/html"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./ssl/certs/www.crt:/etc/nginx/ssl/www.crt:ro"
      - "./ssl/certs/www.key:/etc/nginx/ssl/www.key:ro"

  mariadb:
    # Replace with your own
    image: mariadb:10.4
    container_name: ${APP_NAME}-mariadb
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    networks:
      default:
        ipv4_address: ${IP_BASE}.3
    env_file: env/mysql_maria.env
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./provision/mariadb/create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh

  elasticsearch:
    build:
      context: .
      dockerfile: ./dockerfiles/DockerfileElastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      default:
        ipv4_address: ${IP_BASE}.9
    volumes:
      - ./volumes/es-data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


volumes:

  php_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_APP_PATH}
  
networks:

  default:
    ipam:
      config:
        - subnet: ${IP_BASE}.0/24
          gateway: ${IP_BASE}.1
          ip_range: ${IP_BASE}.128/25